title: Exploring the Impact of Training Dataset Musical Genre and Latent Space Configuration on Latent Sapce Regularisation for Music Generation
description: Songyan Zhao, Berker Banar and Nick Bryan-Kinns

remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
